"""CA & Statutory Tax Audit PDF Report Generator for SET.
Uses ReportLab to generate an official, presentation-ready financial summary PDF.
"""

from __future__ import annotations

import io
from datetime import datetime
from decimal import Decimal
from typing import Optional

from django.db.models import Sum, Count, Min, Max
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.pdfgen import canvas

from tracker.models import Transaction, BankAccount


class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super(NumberedCanvas, self).__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super(NumberedCanvas, self).showPage()
        super(NumberedCanvas, self).save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Header on later pages
        if self._pageNumber > 1:
            self.drawString(54, 750, "SET — Financial Statement & Tax Audit Summary")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 744, 558, 744)

        # Footer on all pages
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 36, page_text)
        self.drawString(54, 36, "Generated by SET (Smart Expense Tracker) · Tax Audit Division")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 46, 558, 46)
        self.restoreState()


def _fmt(val) -> str:
    try:
        f = float(val or 0.0)
        return f"Rs. {f:,.2f}"
    except (ValueError, TypeError):
        return f"Rs. {val}"


def generate_tax_audit_pdf(user, account_id: Optional[int] = None) -> bytes:
    """Generates an official Tax Audit & Books of Accounts Summary PDF."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()

    c_primary = colors.HexColor("#1E3A8A")   # Dark Navy
    c_dark = colors.HexColor("#0F172A")      # Slate 900
    c_body = colors.HexColor("#334155")      # Slate 700
    c_debit = colors.HexColor("#E11D48")     # Rose 600
    c_credit = colors.HexColor("#059669")    # Emerald 600
    c_card_bg = colors.HexColor("#F8FAFC")   # Light slate

    title_style = ParagraphStyle(
        'DocTitle',
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=c_primary,
        spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        'DocSubTitle',
        fontName='Helvetica',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=12
    )
    h1_style = ParagraphStyle(
        'Header1',
        fontName='Helvetica-Bold',
        fontSize=11.5,
        leading=15,
        textColor=c_primary,
        spaceBefore=10,
        spaceAfter=5,
        keepWithNext=True
    )
    body_style = ParagraphStyle(
        'Body',
        fontName='Helvetica',
        fontSize=8.5,
        leading=12,
        textColor=c_body
    )
    body_bold = ParagraphStyle(
        'BodyBold',
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=12,
        textColor=c_dark
    )
    debit_style = ParagraphStyle(
        'DebitText',
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=12,
        textColor=c_debit
    )
    credit_style = ParagraphStyle(
        'CreditText',
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=12,
        textColor=c_credit
    )

    story = []

    # Title & Subtitle
    story.append(Paragraph("FINANCIAL STATEMENT & STATUTORY TAX AUDIT REPORT", title_style))
    story.append(Paragraph("Smart Expense Tracker (SET) · Chartered Accounting & Expenditure Summary", subtitle_style))

    # Fetch Data
    qs = Transaction.objects.select_related("account").filter(user=user)
    if account_id:
        qs = qs.filter(account_id=account_id)

    agg = qs.aggregate(
        total_debit=Sum('debit'),
        total_credit=Sum('credit'),
        total_txns=Count('id'),
        min_date=Min('txn_date'),
        max_date=Max('txn_date'),
    )

    total_debit = Decimal(str(agg['total_debit'] or 0.0))
    total_credit = Decimal(str(agg['total_credit'] or 0.0))
    net_position = total_credit - total_debit
    txn_count = agg['total_txns'] or 0
    date_from = agg['min_date'].strftime('%d %b %Y') if agg['min_date'] else 'N/A'
    date_to = agg['max_date'].strftime('%d %b %Y') if agg['max_date'] else 'N/A'

    accounts = BankAccount.objects.filter(user=user)
    if account_id:
        accounts = accounts.filter(id=account_id)
    acc_names = ", ".join(f"{a.bank_name} ({a.display_account})" for a in accounts) or "All Integrated Accounts"

    # Metadata Grid Table
    user_display = (f"{user.first_name} {user.last_name}").strip() or user.username
    meta_data = [
        [Paragraph("<b>Taxpayer / Account Holder:</b>", body_style), Paragraph(user_display, body_bold),
         Paragraph("<b>Audit Date:</b>", body_style), Paragraph(datetime.now().strftime('%d %b %Y, %I:%M %p'), body_style)],
        [Paragraph("<b>Audited Period:</b>", body_style), Paragraph(f"{date_from} — {date_to}", body_style),
         Paragraph("<b>Total Transactions:</b>", body_style), Paragraph(str(txn_count), body_style)],
        [Paragraph("<b>Bank Accounts In Scope:</b>", body_style), Paragraph(acc_names, body_style),
         Paragraph("<b>Audit Reference ID:</b>", body_style), Paragraph(f"SET-AUDIT-{user.id}-{int(datetime.now().timestamp())}", body_style)],
    ]
    t_meta = Table(meta_data, colWidths=[120, 160, 100, 124])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), c_card_bg),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 10))

    # Executive Summary Table
    story.append(Paragraph("1. Executive Financial Summary", h1_style))
    summary_data = [
        [Paragraph("<b>Metric Description</b>", body_bold), Paragraph("<b>Classification</b>", body_bold), Paragraph("<b>Amount (INR)</b>", body_bold)],
        [Paragraph("Gross Inflows (Income / Deposits)", body_style), Paragraph("Total Credit", credit_style), Paragraph(_fmt(total_credit), credit_style)],
        [Paragraph("Gross Outflows (Expenditures / Payments)", body_style), Paragraph("Total Debit", debit_style), Paragraph(_fmt(total_debit), debit_style)],
        [Paragraph("Net Cashflow Balance", body_style), Paragraph("Surplus" if net_position >= 0 else "Deficit", body_bold), Paragraph(_fmt(net_position), credit_style if net_position >= 0 else debit_style)],
    ]
    t_summary = Table(summary_data, colWidths=[240, 134, 130])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
        ('PADDING', (0,0), (-1,-1), 5),
        ('BACKGROUND', (0,-1), (-1,-1), colors.HexColor("#F8FAFC")),
    ]))
    story.append(t_summary)
    story.append(Spacer(1, 10))

    # Statutory Tax, GST & Professional Fees Breakdown
    story.append(Paragraph("2. Statutory Tax Deductions & Business Compliance Outflows", h1_style))
    tax_qs = qs.filter(category="Taxes/GST").aggregate(total=Sum('debit'), count=Count('id'))
    prof_qs = qs.filter(category="Professional Fees").aggregate(total=Sum('debit'), count=Count('id'))
    inv_qs = qs.filter(category="Investments").aggregate(total=Sum('debit'), count=Count('id'))
    atm_qs = qs.filter(description__icontains="atm").aggregate(total=Sum('debit'), count=Count('id'))

    tax_data = [
        [Paragraph("<b>Tax & Compliance Category</b>", body_bold), Paragraph("<b>Transactions</b>", body_bold), Paragraph("<b>Total Remitted (INR)</b>", body_bold)],
        [Paragraph("Statutory Taxes, GST, TDS & Advance Tax", body_style), Paragraph(str(tax_qs['count'] or 0), body_style), Paragraph(_fmt(tax_qs['total']), body_bold)],
        [Paragraph("Professional, Legal & CA Retainer Fees", body_style), Paragraph(str(prof_qs['count'] or 0), body_style), Paragraph(_fmt(prof_qs['total']), body_bold)],
        [Paragraph("Capital Investments & Wealth Deployments", body_style), Paragraph(str(inv_qs['count'] or 0), body_style), Paragraph(_fmt(inv_qs['total']), body_bold)],
        [Paragraph("Petty Cash / Unallocated ATM Withdrawals", body_style), Paragraph(str(atm_qs['count'] or 0), body_style), Paragraph(_fmt(atm_qs['total']), body_bold)],
    ]
    t_tax = Table(tax_data, colWidths=[264, 110, 130])
    t_tax.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
        ('PADDING', (0,0), (-1,-1), 5),
    ]))
    story.append(t_tax)
    story.append(Spacer(1, 10))

    # Category Wise Breakdown
    story.append(Paragraph("3. Category-Wise Outflow Distribution", h1_style))
    cat_stats = (
        qs.values('category')
        .annotate(spent=Sum('debit'), count=Count('id'))
        .filter(spent__gt=0)
        .order_by('-spent')
    )
    cat_rows = [
        [Paragraph("<b>Category</b>", body_bold), Paragraph("<b>Amount Spent (INR)</b>", body_bold), Paragraph("<b>% of Total Spend</b>", body_bold), Paragraph("<b>Transactions</b>", body_bold)]
    ]
    for c in cat_stats:
        spent = float(c['spent'] or 0.0)
        pct = (spent / float(total_debit) * 100) if total_debit > 0 else 0.0
        cat_rows.append([
            Paragraph(c['category'], body_style),
            Paragraph(_fmt(spent), body_style),
            Paragraph(f"{pct:.1f}%", body_style),
            Paragraph(str(c['count']), body_style),
        ])
    if len(cat_rows) == 1:
        cat_rows.append([Paragraph("No debit transactions recorded.", body_style), Paragraph("—", body_style), Paragraph("—", body_style), Paragraph("—", body_style)])

    t_cats = Table(cat_rows, colWidths=[184, 120, 100, 100])
    t_cats.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
        ('PADDING', (0,0), (-1,-1), 4.5),
    ]))
    story.append(t_cats)
    story.append(Spacer(1, 10))

    # Top 5 Outflow Transactions
    story.append(Paragraph("4. Largest Outflow Transactions (Materiality Audit)", h1_style))
    top_txns = qs.filter(debit__gt=0).order_by('-debit')[:5]
    top_rows = [
        [Paragraph("<b>Date</b>", body_bold), Paragraph("<b>Company / Vendor / Narration</b>", body_bold), Paragraph("<b>Category</b>", body_bold), Paragraph("<b>Debit (INR)</b>", body_bold)]
    ]
    for t in top_txns:
        top_rows.append([
            Paragraph(t.txn_date.strftime('%d %b %Y') if t.txn_date else "—", body_style),
            Paragraph(f"<b>{t.entity_name}</b><br/><font color='#64748B' size='7'>{t.description[:42]}</font>", body_style),
            Paragraph(t.category or "Other", body_style),
            Paragraph(_fmt(t.debit), debit_style),
        ])
    if len(top_rows) == 1:
        top_rows.append([Paragraph("No debits recorded.", body_style), Paragraph("—", body_style), Paragraph("—", body_style), Paragraph("—", body_style)])

    t_top = Table(top_rows, colWidths=[90, 214, 100, 100])
    t_top.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
        ('PADDING', (0,0), (-1,-1), 4.5),
    ]))
    story.append(t_top)
    story.append(Spacer(1, 14))

    # Sign-off & Audit Certification Stamp
    cert_text = (
        "<b>AUDITOR CERTIFICATION:</b> This electronic statement has been compiled from verified and deduplicated "
        "banking statement files uploaded to the Smart Expense Tracker (SET) platform. All ledger entries, currency conversions, "
        "and statutory tax categories have been computed in compliance with standard double-entry financial accounting principles."
    )
    t_cert = Table([[Paragraph(cert_text, body_style)]], colWidths=[504])
    t_cert.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t_cert)

    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()
